use angeles;
insert into gri(nombre)values('Cuadro Básico - Central de Equipos y Esterilización');
insert into gri(nombre)values('Cuadro Básico - Estomatología');
insert into gri(nombre)values('Cuadro Básico - Ginecología y Obstetricia');
insert into gri(nombre)values('Cuadro Básico - Médicas y Quirúrgicas');
insert into gri(nombre)values('Cuadro Básico - Medicina Preventiva');
insert into gri(nombre)values('Cuadro Básico - Planificación Familiar');
insert into gri(nombre)values('Material de Curación - Anestesiología');
insert into gri(nombre)values('Material de Curación - Cardiología Intervencionista');
insert into gri(nombre)values('Material de Curación - Cardiología de Uso General');
insert into gri(nombre)values('Material de Curación - Central de Equipos y Esterilización');
insert into gri(nombre)values('Material de Curación - Cirugía Cardiotorácica y Cardiovascular');
insert into gri(nombre)values('Material de Curación - Cirugía General');
insert into gri(nombre)values('Material de Curación - Cirugía Máxilofacial');
insert into gri(nombre)values('Material de Curación - Cirugía Reconstructiva');
insert into gri(nombre)values('Material de Curación - Estomatología');
insert into gri(nombre)values('Material de Curación - Fisiología Pulmonar');
insert into gri(nombre)values('Material de Curación - Ginecología y Obstetricia');
insert into gri(nombre)values('Material de Curación - Médicas y Quirúrgicas');
insert into gri(nombre)values('Material de Curación - Nefrología o Cirugía General');
insert into gri(nombre)values('Material de Curación - Neurocirugía, Neuroradiología y Terapia Neuroendovascular');
insert into gri(nombre)values('Material de Curación - Oftalmología');
insert into gri(nombre)values('Material de Curación - Otorrinolaringología');
insert into gri(nombre)values('Material de Curación - Quirúrgicas');
insert into gri(nombre)values('Material de Curación - Radiodiagnóstico');
insert into gri(nombre)values('Material de Curación - Traumatología y Ortopedia');
insert into gri(nombre)values('Material de Curación - Urología');
insert into gri(nombre)values('Material de Curación - Materiales de Uso Diverso');
insert into gri(nombre)values('Material de Curación - Materiales de ostesíntesis');
insert into gri(nombre)values('Material de Curación - Sistemas de ostesíntesis');
insert into gri(nombre)values('Material de Curación - Materiales de endoprótesis');
insert into gri(nombre)values('Material de Curación - Sistemas de endoprótesis');
insert into gri(nombre)values('Instrumental - Básico');
insert into gri(nombre)values('Instrumental - Catálogo');
insert into gri(nombre)values('Equipo Médico - Electrónica médica');
insert into gri(nombre)values('Equipo Médico - Imagenología ');
insert into gri(nombre)values('Equipo Médico - Implantables');
insert into gri(nombre)values('Equipo Médico - Mecánica y fluidos');
insert into gri(nombre)values('Equipo Médico - Medicina física y rehabilitación');
insert into gri(nombre)values('Equipo Médico - Medicina nuclear ');
insert into gri(nombre)values('Equipo Médico - Oftalmología');
insert into gri(nombre)values('Equipo Médico - Óptica ');
insert into gri(nombre)values('Equipo Médico - Prótesis ');
insert into gri(nombre)values('Equipo Médico - Quirófano');
insert into gri(nombre)values('Equipo Médico - Radioterapia');
insert into gri(nombre)values('Medicamentos - Agentes Digestivos, Incluyendo Enzimas');
insert into gri(nombre)values('Medicamentos - Antieméticos');
insert into gri(nombre)values('Medicamentos - Anticoagulantes no Inyectables');
insert into gri(nombre)values('Medicamentos - Anticoagulantes Inyectables');
insert into gri(nombre)values('Medicamentos - Inhibidores de la Agregación Plaquetaria');
insert into gri(nombre)values('Medicamentos - Fibrinolíticos');
insert into gri(nombre)values('Medicamentos - Inhibidores Directos De La Trombina');
insert into gri(nombre)values('Medicamentos - Otros Agentes Trombóticos');
insert into gri(nombre)values('Medicamentos - Agentes Tópicos para el Tratamiento de la Psoriasis');
insert into gri(nombre)values('Medicamentos - Agentes Sistémicos para el Tratamiento de la Psoriasis y Productos Similares');
insert into gri(nombre)values('Medicamentos - Otros Productos no Esteroides para Tratar Trastornos Inflamatorios de la Piel');
insert into gri(nombre)values('Medicamentos - Anti Infecciosos Óticos');
insert into gri(nombre)values('Medicamentos - Combinaciones de Corticosteroides con Antiinfecciosos');
insert into gri(nombre)values('Medicamentos - Otros Productos Óticos');
insert into gri(nombre)values('Medicamentos - Preparados adelgazantes');
insert into gri(nombre)values('Medicamentos - Suplementos Proteínicos');
insert into gri(nombre)values('Medicamentos - Fórmulas Infantiles');
insert into gri(nombre)values('Medicamentos - Otros Nutrientes');
insert into gri(nombre)values('Medicamentos - Agentes Inmunoestimulantes Excepto los Interferones');
insert into gri(nombre)values('Medicamentos - Interferones');
insert into gri(nombre)values('Medicamentos - Agentes Inmunosupresores Selectivos');
insert into gri(nombre)values('Medicamentos - Agentes Curativos, Heridas');
insert into gri(nombre)values('Medicamentos - Glucósidos Cardioactivos y sus Combinaciones');
insert into gri(nombre)values('Medicamentos - Antiarrítmicos');
insert into gri(nombre)values('Medicamentos - Estimulantes Cardiacos Excluyendo a los Glucósidos Cardioactivos');
insert into gri(nombre)values('Medicamentos - Terapia Coronaria, Excluyendo Antagonistas del Calcio / Nitritos');
insert into gri(nombre)values('Medicamentos - Nitritos y Nitratos');
insert into gri(nombre)values('Medicamentos - Agentes Inotrópicos Positivos');
insert into gri(nombre)values('Medicamentos - Todas las Demás Preparaciones para el Corazón');
insert into gri(nombre)values('Medicamentos - Inhibidores de la ECA Solos');
insert into gri(nombre)values('Medicamentos - Inhibidores de la ECA Combinados');
insert into gri(nombre)values('Medicamentos - Antagonistas de la Angiotensina II Solos');
insert into gri(nombre)values('Medicamentos - Antagonistas de la Angiotensina II Combinados');
insert into gri(nombre)values('Medicamentos - Otros Agentes Activos En El Sistema De Angiotensinas Reninas');
insert into gri(nombre)values('Medicamentos - Medicamentos para el Tratamiento de las Enfermedades Vasculares Cerebrales y Periféricas');
insert into gri(nombre)values('Medicamentos - Agentes para Infecciones Fúngicas Sistemicas');
insert into gri(nombre)values('Medicamentos - Hormonas Anabólicas Sistémicas');
insert into gri(nombre)values('Medicamentos - Otros Agentes Anabólicos Sistémicos');
insert into gri(nombre)values('Medicamentos - Narcóticos');
insert into gri(nombre)values('Medicamentos - No Narcóticos y Antipiréticos');
insert into gri(nombre)values('Medicamentos - Preparaciones en contra de la Migraña');
insert into gri(nombre)values('Medicamentos - Anestésicos Generales');
insert into gri(nombre)values('Medicamentos - Anestésicos Locales');
insert into gri(nombre)values('Medicamentos - Calcioantagonistas Solos');
insert into gri(nombre)values('Medicamentos - Calcioantagonistas Combinados');
insert into gri(nombre)values('Medicamentos - Antiácidos, Antiflatulentos y Carminativos');
insert into gri(nombre)values('Medicamentos - Antiulcerosos');
insert into gri(nombre)values('Medicamentos - Tetraciclinas y Combinaciones');
insert into gri(nombre)values('Medicamentos - Cloramfenicol y Combinaciones');
insert into gri(nombre)values('Medicamentos - Penicilinas de Amplio Espectro');
insert into gri(nombre)values('Medicamentos - Cefalosporinas');
insert into gri(nombre)values('Medicamentos - Trimetroprim y Sustancias Similares');
insert into gri(nombre)values('Medicamentos - Macrólidos y Similares');
insert into gri(nombre)values('Medicamentos - Fluoroquinolonas');
insert into gri(nombre)values('Medicamentos - Penicilinas de Espectro Medio y Reducido');
insert into gri(nombre)values('Medicamentos - Aminoglucósidos');
insert into gri(nombre)values('Medicamentos - Carbenicilina y Similares');
insert into gri(nombre)values('Medicamentos - Rifampicina-Rifamicina');
insert into gri(nombre)values('Medicamentos - Otros Antibacterianos Beta-Lactámicos, Excluyendo Penicilinas y Cefalosporinas');
insert into gri(nombre)values('Medicamentos - Otros Antibióticos');
insert into gri(nombre)values('Medicamentos - Antiepilépticos');
insert into gri(nombre)values('Medicamentos - Antidiarreicos con Efecto Antiinfeccioso a Nivel Intestinal');
insert into gri(nombre)values('Medicamentos - Antidiarreicos y Absorbentes');
insert into gri(nombre)values('Medicamentos - Formulacion de Sales de Hidratación Oral');
insert into gri(nombre)values('Medicamentos - Agentes Antiinflamatorios Intestinales');
insert into gri(nombre)values('Medicamentos - Microorganismos Usados Como Antidiarreicos');
insert into gri(nombre)values('Medicamentos - Tratamiento de Reemplazo Oral con Electrólitos');
insert into gri(nombre)values('Medicamentos - Inhibidores de la Motilidad');
insert into gri(nombre)values('Medicamentos - Todos los Demás Antidiarreicos');
insert into gri(nombre)values('Medicamentos - Antiespasmódicos y Anticolinérgicos Solos');
insert into gri(nombre)values('Medicamentos - Combinaciones de Antiespasmódicos con Ataráxicos');
insert into gri(nombre)values('Medicamentos - Combinaciones de Analgésicos con Antiespasmódicos');
insert into gri(nombre)values('Medicamentos - Antiespasmódicos Combinados con otros Productos');
insert into gri(nombre)values('Medicamentos - Gastroprocinéticos');
insert into gri(nombre)values('Medicamentos - Moduladores Sensorimotores');
insert into gri(nombre)values('Medicamentos - Antagonistas (Antidotos de los Anticoagulantes)');
insert into gri(nombre)values('Medicamentos - Inhibidores de Proteinasas');
insert into gri(nombre)values('Medicamentos - Coagulación sanguínea');
insert into gri(nombre)values('Medicamentos - Hemostáticos Sistémicos');
insert into gri(nombre)values('Medicamentos - Antihipertensivos Solos (No Herbolarios)');
insert into gri(nombre)values('Medicamentos - Alcaloides de la Rawolfia y Otros Agentes Fitoterapéuticos Antihipertensivos Combinados con Diuréticos');
insert into gri(nombre)values('Medicamentos - Otros Antihipertensivos');
insert into gri(nombre)values('Medicamentos - Antihistamínicos Sistémicos');
insert into gri(nombre)values('Medicamentos - Tricomonicidas');
insert into gri(nombre)values('Medicamentos - Antimicóticos Ginecológicos');
insert into gri(nombre)values('Medicamentos - Antibióticos y Sulfonamidas');
insert into gri(nombre)values('Medicamentos - Antisépticos Ginecológicos');
insert into gri(nombre)values('Medicamentos - Antirreumáticos no Esteroideos');
insert into gri(nombre)values('Medicamentos - Antirreumáticos Corticosteroideos en Combinación');
insert into gri(nombre)values('Medicamentos - Antirreumáticos Específicos');
insert into gri(nombre)values('Medicamentos - Productos para el Tratamiento de la Tuberculosis');
insert into gri(nombre)values('Medicamentos - Productos para el Tratamiento de la Lepra');
insert into gri(nombre)values('Medicamentos - Antimicóticos de Uso Dermatológico');
insert into gri(nombre)values('Medicamentos - Agentes Alquilantes');
insert into gri(nombre)values('Medicamentos - Antimetabolitos');
insert into gri(nombre)values('Medicamentos - Alcaloides de la Vinca y Otros Productos de Plantas');
insert into gri(nombre)values('Medicamentos - Antibióticos Antineoplásicos');
insert into gri(nombre)values('Medicamentos - Otros Antineoplásicos');
insert into gri(nombre)values('Medicamentos - Antipruriginosos, Incluyendo Antihistamínicos Tópicos, Anestésicos, Etc.');
insert into gri(nombre)values('Medicamentos - Antirreumáticos Tópicos');
insert into gri(nombre)values('Medicamentos - Antisépticos Quirúigicos');
insert into gri(nombre)values('Medicamentos - Antisépticos y Desinfectantes Tópicos');
insert into gri(nombre)values('Medicamentos - Agentes Tópicos para el Tratamiento de las Hemorroides');
insert into gri(nombre)values('Medicamentos - Tratamientos Tópicos para las Venas Varicosas');
insert into gri(nombre)values('Medicamentos - Tratamientos Sistémicos para las Venas Varicosas');
insert into gri(nombre)values('Medicamentos - Agentes de Accion Directa');
insert into gri(nombre)values('Medicamentos - Antivirales, Excluyendo Productos Anti-VIH');
insert into gri(nombre)values('Medicamentos - Antivirales para VIH');
insert into gri(nombre)values('Medicamentos - Antibióticos y Sulfonamidas de Uso Tópico');
insert into gri(nombre)values('Medicamentos - Productos Tópicos para el Tratamiento de las Infecciones Virales');
insert into gri(nombre)values('Medicamentos - Contraceptivos Físicos');
insert into gri(nombre)values('Medicamentos - Equipos Médicos de Medición');
insert into gri(nombre)values('Medicamentos - Beta Bloqueadores Solos');
insert into gri(nombre)values('Medicamentos - Agentes Beta Bloqueadores Combinados');
insert into gri(nombre)values('Medicamentos - Terapéutica Biliar y Colagogos');
insert into gri(nombre)values('Medicamentos - Protectores Hepáticos y Lipotrópicos');
insert into gri(nombre)values('Medicamentos - Corticosteroides Sistémicos, Puros');
insert into gri(nombre)values('Medicamentos - Combinaciones de Corticosteroides Sistémicos');
insert into gri(nombre)values('Medicamentos - Corticosteroides Tópicos Solos');
insert into gri(nombre)values('Medicamentos - Combinaciones de Corticoesteroides Tópicos');
insert into gri(nombre)values('Medicamentos - Diuréticos');
insert into gri(nombre)values('Medicamentos - Ectoparasiticidas, Incluyendo Escabicidas.');
insert into gri(nombre)values('Medicamentos - Insecticidas y Repelentes');
insert into gri(nombre)values('Medicamentos - Emolientes y Protectores');
insert into gri(nombre)values('Medicamentos - Enzimas Antiinflamatorias');
insert into gri(nombre)values('Medicamentos - Estimulantes del Apetito');
insert into gri(nombre)values('Medicamentos - Estomatológicos');
insert into gri(nombre)values('Medicamentos - Gelatina en Soluciones');
insert into gri(nombre)values('Medicamentos - Agentes para la Reducción de las Concentraciones de Colesterol y Triglicéridos');
insert into gri(nombre)values('Medicamentos - Hormonas anti Hormona Paratiroidea');
insert into gri(nombre)values('Medicamentos - Hormonas del Lóbulo Anterior de la Hipófisis y Análogos');
insert into gri(nombre)values('Medicamentos - Gonadotropina-Hormonas Liberadoras');
insert into gri(nombre)values('Medicamentos - Anticonceptivos Hormonales Sistémicos');
insert into gri(nombre)values('Medicamentos - Andrógenos, Excluyendo G3E, G3F');
insert into gri(nombre)values('Medicamentos - Estrógenos, Excluyendo G3A, G3E, G3F');
insert into gri(nombre)values('Medicamentos - Progestágenos, Excluyendo G3A, G3F');
insert into gri(nombre)values('Medicamentos - Combinaciones de Andrógenos con Hormonas Femeninas');
insert into gri(nombre)values('Medicamentos - Estrógenos Combinados con Progestágenos, Excluyendo G3A');
insert into gri(nombre)values('Medicamentos - Gonadotropinas , Incluyendo Otros Estimulantes de la Ovulación');
insert into gri(nombre)values('Medicamentos - Otras Hormonas Sexuales');
insert into gri(nombre)values('Medicamentos - Moduladores Selectivos de Receptores de Estrogeno');
insert into gri(nombre)values('Medicamentos - Otras Hormonas Sexuales Y Productos Similares');
insert into gri(nombre)values('Medicamentos - Laxantes');
insert into gri(nombre)values('Medicamentos - Apósito de espesor parcial o completo');
insert into gri(nombre)values('Medicamentos - Accesorio para Venoclisis');
insert into gri(nombre)values('Medicamentos - Medicamentos contra el Mal de Parkinson');
insert into gri(nombre)values('Medicamentos - Insulinas Humanas y sus Análogos');
insert into gri(nombre)values('Medicamentos - Sulfonilureas');
insert into gri(nombre)values('Medicamentos - Biguanidas Antidiabéticas');
insert into gri(nombre)values('Medicamentos - Glitazonas, Antidiabéticos Orales (Tiazolidinedionas)');
insert into gri(nombre)values('Medicamentos - Inhibidores de la Alfa Glucosidasa');
insert into gri(nombre)values('Medicamentos - Antidiabéticos Orales Glinidas');
insert into gri(nombre)values('Medicamentos - Inhibidores de la DPP IV');
insert into gri(nombre)values('Medicamentos - GLP-1 Agonistas Antidiabéticos');
insert into gri(nombre)values('Medicamentos - Otros Medicamentos Usados para el Tratamiento de la Diabetes');
insert into gri(nombre)values('Medicamentos - Medios de Contraste para Rayos X no Iodados');
insert into gri(nombre)values('Medicamentos - Anti-Infecciosos de Uso Oftalmológico');
insert into gri(nombre)values('Medicamentos - Corticoesteroides Oftalmológicos');
insert into gri(nombre)values('Medicamentos - Combinaciones de Corticoesteroides con Agentes Antiinfecciosos');
insert into gri(nombre)values('Medicamentos - Agentes Antivirales Oftalmológicos');
insert into gri(nombre)values('Medicamentos - Mióticos y Preparaciones contra el Glaucoma');
insert into gri(nombre)values('Medicamentos - Midriaticos y Cicloplegicos');
insert into gri(nombre)values('Medicamentos - Preparaciones para el Tratamiento de la Conjuntivitis Inespecífica');
insert into gri(nombre)values('Medicamentos - Lagrimas Artificiales y Lubricantes Oculares');
insert into gri(nombre)values('Medicamentos - Soluciones para Lentes de Contacto');
insert into gri(nombre)values('Medicamentos - Productos Oftalmológicos para la Antineovascularización');
insert into gri(nombre)values('Medicamentos - Antiinflamatorios no Esteroideos de Uso Oftálmico');
insert into gri(nombre)values('Medicamentos - Otros Oftalmológicos');
insert into gri(nombre)values('Medicamentos - Medicamentos Parasimpatomiméticos');
insert into gri(nombre)values('Medicamentos - Productos Antitabaquismo');
insert into gri(nombre)values('Medicamentos - Productos contra el Vértigo');
insert into gri(nombre)values('Medicamentos - Productos contra la Enfermedad de Alzheimer');
insert into gri(nombre)values('Medicamentos - Medicamentos Usados para el Tratamiento del Alcoholismo');
insert into gri(nombre)values('Medicamentos - Todas las Demás Drogas que Actúan Sobre el SNC');
insert into gri(nombre)values('Medicamentos - Calcitoninas');
insert into gri(nombre)values('Medicamentos - Glucagon');
insert into gri(nombre)values('Medicamentos - Hormonas de Crecimiento');
insert into gri(nombre)values('Medicamentos - Hormonas Antidiuréticas');
insert into gri(nombre)values('Medicamentos - Hormonas Paratiroideas y Análogos');
insert into gri(nombre)values('Medicamentos - Otras Hormonas y Compuestos con Acción Similar');
insert into gri(nombre)values('Medicamentos - Otras Hormonas y Preparados con efectos Similares');
insert into gri(nombre)values('Medicamentos - Otras Preparaciones Dermatológicas');
insert into gri(nombre)values('Medicamentos - Anaerobicidas');
insert into gri(nombre)values('Medicamentos - Reguladores del Calcio Óseo');
insert into gri(nombre)values('Medicamentos - Otros Productos para Tratar el Sistema Musculoesquelético');
insert into gri(nombre)values('Medicamentos - Otros Medicamentos Para desordenes del Sistema Musculoesquelético');
insert into gri(nombre)values('Medicamentos - Otros Productos Cardiovasculares');
insert into gri(nombre)values('Medicamentos - Inductores del Trabajo de Parto');
insert into gri(nombre)values('Medicamentos - Anticonceptivos Tópicos');
insert into gri(nombre)values('Medicamentos - Inhibidores de la Producción de Prolactina');
insert into gri(nombre)values('Medicamentos - Inhibidores del Trabajo de Parto');
insert into gri(nombre)values('Medicamentos - Hormonas Sexuales Tópicas');
insert into gri(nombre)values('Medicamentos - Otros Productos Ginecológicos');
insert into gri(nombre)values('Medicamentos - Otros Productos que Actúan Sobre el Metabolismo y el Tracto Gastrointestinal');
insert into gri(nombre)values('Medicamentos - Estimulantes Respiratorios');
insert into gri(nombre)values('Medicamentos - Otros Productos del Sistema Respiratorio');
insert into gri(nombre)values('Medicamentos - Demás Productos Terapéuticos');
insert into gri(nombre)values('Medicamentos - Agentes Destoxificantes o Protectores para el Tratamiento Antineoplásico');
insert into gri(nombre)values('Medicamentos - Agentes Quelantes del Hierro');
insert into gri(nombre)values('Medicamentos - Productos para la Hiperfosfatemia y para la Hiperkalemia');
insert into gri(nombre)values('Medicamentos - Otros Productos Terapéuticos');
insert into gri(nombre)values('Medicamentos - Hematínicos, Hierro y sus Combinaciones');
insert into gri(nombre)values('Medicamentos - Productos con Eritropoyetina');
insert into gri(nombre)values('Medicamentos - Otros Productos Antianémicos Como el Ácido Fólico y Folínico');
insert into gri(nombre)values('Medicamentos - Preparaciones Antigotosas');
insert into gri(nombre)values('Medicamentos - Agonistas-B2');
insert into gri(nombre)values('Medicamentos - Xantinas');
insert into gri(nombre)values('Medicamentos - Antiinflamatorios No Esteroideos');
insert into gri(nombre)values('Medicamentos - Corticoides');
insert into gri(nombre)values('Medicamentos - Combinaciones de Agonistas B-2 con Corticoides');
insert into gri(nombre)values('Medicamentos - Anticolinérgicos Sencillos y sus Combinaciones con Agonistas-B2');
insert into gri(nombre)values('Medicamentos - Dispositivos para Condiciones Asmáticas');
insert into gri(nombre)values('Medicamentos - Antiasmáticos Antileucotrieno');
insert into gri(nombre)values('Medicamentos - Todos los Demás Productos para Asma y Epoc');
insert into gri(nombre)values('Medicamentos - Formulaciones Tópicas contra el Acné');
insert into gri(nombre)values('Medicamentos - Preparaciones Orales contra el Acné');
insert into gri(nombre)values('Medicamentos - Preparaciones contra la Obesidad, Excluyendo los Agentes Dietéticos');
insert into gri(nombre)values('Medicamentos - Preparaciones contra el Resfriado Sin Agentes Antiinfecciosos');
insert into gri(nombre)values('Medicamentos - Preparaciones contra el Resfriado-Tos con Agentes Antiinfecciosos');
insert into gri(nombre)values('Medicamentos - Expectorantes');
insert into gri(nombre)values('Medicamentos - Antitusivos');
insert into gri(nombre)values('Medicamentos - Preparaciones Nasales Tópicas');
insert into gri(nombre)values('Medicamentos - Preparaciones Nasales Sistémicas');
insert into gri(nombre)values('Medicamentos - Preparados para la Garganta');
insert into gri(nombre)values('Medicamentos - Amebicidas');
insert into gri(nombre)values('Medicamentos - Antihelmínticos, Excluyendo Esquistomicidas');
insert into gri(nombre)values('Medicamentos - Antimaláricos');
insert into gri(nombre)values('Medicamentos - Escabicidas y Ectoparsiticidas');
insert into gri(nombre)values('Medicamentos - Reguladores de Lípidos para Terápia Múltiple Cardiovascular');
insert into gri(nombre)values('Medicamentos - Pruebas de Embarazo y Ovulación');
insert into gri(nombre)values('Medicamentos - Antidepresivos y Estabilizadores del Ánimo');
insert into gri(nombre)values('Medicamentos - Psicoestimulantes');
insert into gri(nombre)values('Medicamentos - Psicolepticos / Psicoanalépticos');
insert into gri(nombre)values('Medicamentos - Nootrópicos (Noosténicos)');
insert into gri(nombre)values('Medicamentos - Neurotónicos y Otros Productos Misceláneos');
insert into gri(nombre)values('Medicamentos - Antipsicóticos');
insert into gri(nombre)values('Medicamentos - Hipnóticos-Sedantes');
insert into gri(nombre)values('Medicamentos - Tranquilizantes');
insert into gri(nombre)values('Medicamentos - Relajantes Musculares de Acción Periférica');
insert into gri(nombre)values('Medicamentos - Relajantes Musculares de Acción Central');
insert into gri(nombre)values('Medicamentos - Revulsivos y Otros Inhalantes');
insert into gri(nombre)values('Medicamentos - Soluciones Protéicas');
insert into gri(nombre)values('Medicamentos - Soluciones con Electrolitos (>=100 Ml)');
insert into gri(nombre)values('Medicamentos - Soluciones Estándar');
insert into gri(nombre)values('Medicamentos - Soluciones con Aminoácidos');
insert into gri(nombre)values('Medicamentos - Soluciones para Infusión Especial');
insert into gri(nombre)values('Medicamentos - Soluciones Electrolíticas (<100 ML)');
insert into gri(nombre)values('Medicamentos - Otras Soluciones Inyectables Infusiones Aditivas');
insert into gri(nombre)values('Medicamentos - Soluciones Peritoneo Dialíticas');
insert into gri(nombre)values('Medicamentos - Material Postquirúrgico');
insert into gri(nombre)values('Medicamentos - Sueros Antitoxinas');
insert into gri(nombre)values('Medicamentos - Inmunoglobulinas Polivalentes, Intravenosas');
insert into gri(nombre)values('Medicamentos - Inmunoglobulinas Específicas Antibacterianas');
insert into gri(nombre)values('Medicamentos - Otras Inmunoglobulinas Específicas');
insert into gri(nombre)values('Medicamentos - Productos con Calcio');
insert into gri(nombre)values('Medicamentos - Productos con Potasio');
insert into gri(nombre)values('Medicamentos - Otros suplementos Minerales');
insert into gri(nombre)values('Medicamentos - Preparaciones con Hormonas Tiroideas');
insert into gri(nombre)values('Medicamentos - Preparaciones Antitiroideas');
insert into gri(nombre)values('Medicamentos - Hormonas Citostáticas');
insert into gri(nombre)values('Medicamentos - Antagonistas de Hormonas Citostáticas');
insert into gri(nombre)values('Medicamentos - Antagonistas de las Hormonas Citostáticas');
insert into gri(nombre)values('Medicamentos - Anti-Infecciosos y Antisépticos Urinarios');
insert into gri(nombre)values('Medicamentos - Otras Preparaciones Urológicas');
insert into gri(nombre)values('Medicamentos - Productos para la Hiperplásia Prostática Benigna');
insert into gri(nombre)values('Medicamentos - Productos Para la Incontinencia Urinaria');
insert into gri(nombre)values('Medicamentos - Otros Productos Urológicos');
insert into gri(nombre)values('Medicamentos - Vacunas Puras');
insert into gri(nombre)values('Medicamentos - Combinaciones de Vacunas');
insert into gri(nombre)values('Medicamentos - Otras Vacunas');
insert into gri(nombre)values('Medicamentos - Multivitaminas con Minerales');
insert into gri(nombre)values('Medicamentos - Multivitaminas Sin Minerales');
insert into gri(nombre)values('Medicamentos - Vitaminas A y D, incluyendo las combinaciones de ambas');
insert into gri(nombre)values('Medicamentos - Vitamina B1 y Combinaciones de Vitaminas B1, B6 y B12');
insert into gri(nombre)values('Medicamentos - Complejo B');
insert into gri(nombre)values('Medicamentos - Vitamina B12 Sola');
insert into gri(nombre)values('Medicamentos - Vitamina C Excluyendo Las Combinaciones con Minerales');
insert into gri(nombre)values('Medicamentos - Otros Preparados de Vitaminas');
insert into gri(nombre)values('Medicamentos - Otros Preparados con Vitaminas, Combinaciones');
insert into gri(nombre)values('Medicamentos - Otras Vitaminas');
insert into gri(nombre)values('Medicamentos - Estupefacientes');
insert into gri(nombre)values('Medicamentos - Psicotrópicos');
